--- name:default
# General configuration values to run the task
filter_configuration:
  source_frame_name: 'world'
  target_frame_name: 'imu'
  use_samples_as_theoretical_gravity: true
  use_inclinometers: false
  use_magnetometers: false
  init_leveling_samples: 500

--- name:Bremen
# Localization properties related to the geographic place (i.e.: latitude, longitude, magnetic declination).
location:
  latitude: 0.926978312
  longitude: 0.154608945
  altitude: 12.0
  magnetic_declination: 0.03098929 
  magnetic_declination_mode: 1
  dip_angle: 1.187778974


--- name:imu_kvh_1750
# Adaptive estimation of external acceleration.
adaptive_config_acc:
  M1: 5
  M2: 500
  gamma: 0.0062

# Inertial Sensors property.
inertial_noise:
  bandwidth: 440.0 #Hz for gyro, acc has 200.0 Hz
  gbiasoff:
    data:
    - 0.0 
    - 0.0 
    - 0.0 
  gyrorw:
    data:
    - 3.7e-06 
    - 3.7e-06 
    - 3.7e-06 
  gyrorrw:
    data:
    - 0.0
    - 0.0
    - 0.0
  gbiasins:
    data:
    - 2.42e-07
    - 2.42e-07
    - 2.42e-07
  abiasoff:
    data:
    - 0.0 #-0.0027
    - 0.0 
    - 0.0 #0.0055
  accrw:
    data:
    - 3.302e-04
    - 3.302e-04
    - 3.302e-04
  accrrw:
    data:
    - 0.0
    - 0.0
    - 0.0
  abiasins:
    data:
    - 4.905e-04 
    - 4.905e-04 
    - 4.905e-04 
  accresolut:
    data:
    - 2.993774e-03
    - 2.993774e-03
    - 2.993774e-03
